- name: install nginx
  apt:
    name: nginx
    state: latest

- name: replace file
  ansible.builtin.copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify: Restart nginx service

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes
