- name: install nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: replace file
  ansible.builtin.copy:
    src: /home/administrator/ica0002/roles/nginx/files/index.html
    dest: /var/www/html/index.html
