---
  - name: Install nginx
    apt:
        name: nginx
        state: latest
        update_cache: yes

  - name: Copy config to location
    copy:
      src: default
      dest: /etc/nginx/sites-enabled/default
    notify: Restart nginx service

  - name: Start nginx service
    service:
        name: nginx
        state: started
        enabled: yes
