---
  - name: Install haproxy
    apt:
      name: haproxy
      state: latest

  - name: put haproxy config
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify: restart haproxy service

  - name: Install haproxy exporter
    apt:
      name: prometheus-haproxy-exporter
      state: latest

  - name: add correct args
    template:
      src: prometheus-haproxy-exporter.j2
      dest: /etc/default/prometheus-haproxy-exporter
    notify: restart haproxy exporter service

  - name: start service haproxy
    service:
      name: haproxy
      state: started
      enabled: yes

  - name: start service haproxy exporter
    service:
      name: prometheus-haproxy-exporter
      state: started
      enabled: yes
