---
  - name: Add apt key for influxDB
    ansible.builtin.apt_key:
      url: https://repos.influxdata.com/influxdb.key

  - name: add specified repository into sources list
    ansible.builtin.apt_repository:
      repo: deb https://repos.influxdata.com/ubuntu focal stable

  - name: install influxdb and telegraf
    apt:
      name: 
        - influxdb
        - telegraf

  - name: influxdb configuration
    template:
      src: influxdb.conf.j2
      dest: /etc/influxdb/influxdb.conf
    notify: restart influxdb

  - name: Start service influxdb, if not started
    service:
      name: influxdb
      state: started
      enabled: yes

  - name: Reconfigure Telegraf
    template:
      src: telegraf.conf.j2
      dest: /etc/telegraf/telegraf.conf
    notify: restart telegraf

  - name: Start service telegraf, if not started
    service:
      name: telegraf
      state: started
      enabled: yes
