---
  - name: Install Rsyslog
    apt:
      name: rsyslog
      state: latest

  - name: Reconfigure Rsyslog
    template:
      src: 10-telegraf.conf.j2
      dest: /etc/rsyslog.d/10-telegraf.conf
    notify: restart rsyslog

  - name: start rsyslog
    service:
      name: rsyslog
      state: started
      enabled: yes
