---
  - name: Install required tools for Grafana installation
    apt:
      name: apt-transport-https
      state: latest

  - name: Add an apt key
    apt_key:
      url: https://packages.grafana.com/gpg.key

  - name: Add Grafana repository
    apt_repository:
      filename: grafana
      repo: deb https://packages.grafana.com/oss/deb stable main

  - name: Install Grafana
    apt:
      name: grafana
      state: latest
    notify: reset grafana password

  - name: Start grafana
    service:
        name: grafana-server
        state: started
        enabled: yes

  - name: Reconfigure Grafana
    template:
      src: grafana.ini.j2
      dest: /etc/grafana/grafana.ini
    notify: restart grafana

  - name: prometheus datasource
    template:
      src: prometheus.yaml.j2
      dest: /etc/grafana/provisioning/datasources/prometheus.yaml
    notify: restart grafana

  - name: influxdb datasource
    template:
      src: influx.yaml.j2
      dest: /etc/grafana/provisioning/datasources/influx.yaml
    notify: restart grafana

  - name: telegraf datasource
    template:
      src: telegraf.yaml.j2
      dest: /etc/grafana/provisioning/datasources/telegraf.yaml
    notify: restart grafana
  
  - name: put template config file for dashboards
    template:
      src: dashboard.yaml.j2
      dest: /etc/grafana/provisioning/dashboards/sample.yaml

  - name: Setup dashboards
    copy:
      src: main.json
      dest: /etc/grafana/provisioning/dashboards/main.json
    notify: restart grafana
    