---
  - name: intall uwsgi
    apt:
      name:
        - uwsgi
        - uwsgi-plugin-python3

  - name: Start uwsgi service
    service:
      name: uwsgi
      state: started
      enabled: yes

  - name: Add the configuration agama for agama
    template:
      src: agama.ini
      dest: /etc/uwsgi/apps-enabled/agama.ini
    notify: Restart uwsgi service
    