---
  - name: create dir for agama
    file:
      path: /opt/agama
      state: directory

  - name: install agama
    get_url:
      url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
      dest: /opt/agama/Dockerfile

  - name: build docker image
    community.docker.docker_image:
      name: agama
      source: build
      build:
        path: /opt/agama

  - name: install and start agama
    community.docker.docker_container:
      name: agama
      image: agama
      published_ports: "{{ agama_port }}:8000"
      container_default_behavior: no_defaults
      env:
       AGAMA_DATABASE_URI=mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
