- name: create user agama
  ansible.builtin.user:
    name: agama
    shell: /bin/bash

- name: Create the directory /opt/agama owned by user agama
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    owner: agama

- name: Install application dependencies
  apt: 
    name: python3-flask-sqlalchemy
    state: present

- name: Install the application itself
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama