---
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /home/backup/influxdb
      state: directory
      owner: backup
      group: backup
      mode: '0755'

  - name: put backup template
    ansible.builtin.template:
      src: influxdb-backup.j2
      dest: /etc/cron.d/influxdb-backup
      owner: root
      group: root
