---
  - name: install mysqld exporter
    apt:
      name: prometheus-mysqld-exporter
      state: latest
    #register: prom_exporter_installed

  - name: Create MySQL user exporter
    community.mysql.mysql_user:
      name: "{{ mysql_exporter_user }}"
      password: "{{ mysql_exporter_password }}"
      priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
      login_unix_socket: /var/run/mysqld/mysqld.sock
  
  - name: put template
    template:
      src: my.cnf.j2
      dest: /var/lib/prometheus/.my.cnf
    notify: restart mysqld exporter

  - name: sleep 10 sec
    pause:
      seconds: 10
    #when: prom_exporter_installed.changed

  - name: Start mysql exporter
    service:
      name: prometheus-mysqld-exporter
      state: started
      enabled: yes
