---
  - name: install mysqld exporter
    apt:
      name: prometheus-mysqld-exporter
      state: latest

  - name: Create MySQL user exporter
    community.mysql.mysql_user:
      name: "{{ mysql_exporter_user }}"
      password: "{{ mysql_exporter_password }}"
      priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
      login_unix_socket: /var/run/mysqld/mysqld.sock
  
  - name: put template
    template:
      src: my.cnf.j2
      dest: /var/lib/prometheus/.my.cnf
    notify: restart mysqld exporter
