---
  - name: Exporter packages
    apt:
      name: 
        - prometheus-node-exporter

  - name: Enable node exporter service
    service:
      name: prometheus-node-exporter
      state: started
      enabled: yes
    become: yes
