---
  - name: Install fping
    apt:
      name: fping
      state: latest

  - name: Install curl
    apt:
      name: curl
      state: latest

  - name: Add the user "pinger"
    user:
      name: pinger

  - name: Create pinger configuration directory
    file:
      path: /etc/pinger
      state: directory
      mode: '0751'

  - name: Create pinger configuration
    template:
      src: pinger.conf.j2
      dest: /etc/pinger/pinger.conf
    notify: restart pinger

  - name: Place script to /usr/local/bin/pinger
    template:
      src: pinger.sh.j2
      dest: /usr/local/bin/pinger
      mode: '0777'
    notify: restart pinger

  - name: Create pinger service
    template:
      src: pinger.service.j2
      dest: /etc/systemd/system/pinger.service
    notify: 
      - reload systemd
      - restart pinger
