---
  - name: install bind exporter
    apt:
      name: prometheus-bind-exporter

  - name: enable bind exporter
    service:
      name: prometheus-bind-exporter
      state: started
      enabled: yes 
