---
  - name: Install keepalived
    apt:
      name: keepalived
      state: latest

  - name: creater keepalivescript user
    ansible.builtin.user:
      name: keepalived_script
      shell: /bin/bash

  - name: put keepalived script
    template:
      src: keepalived_script.j2
      dest: /home/keepalived_script/keepalived_script
      mode: 0755

  - name: put keepalived config
    template:
      src: keepalived.conf.j2
      dest: /etc/keepalived/keepalived.conf
    notify: restart keepalived service

  - name: start service keepalived
    service:
      name: keepalived
      state: started
      enabled: yes
