---
  - name: download and unzip archive with exporter
    unarchive:
      src: http://backup/keepalived-exporter-1.2.0.linux-amd64.tar.gz
      dest: /usr/local/bin
      remote_src: yes

  - name: copy keepalived exporter
    copy:
      src: /usr/local/bin/keepalived-exporter-1.2.0.linux-amd64/keepalived-exporter
      dest: /usr/local/bin/prometheus-keepalived-exporter
      remote_src: yes
      mode: 0755

  - name: create service
    template:
      src: prometheus-keepalived-exporter.service.j2
      dest: /etc/systemd/system/prometheus-keepalived-exporter.service
    notify:
      - restart keepalived exporter
      - reload systemd

  - name: start enable keepalived exporter
    service:
      name: prometheus-keepalived-exporter
      state: started
      enabled: yes
