---
  - name: Install Prometheus
    apt:
      name: prometheus
      state: latest

  - name: Configure Prometheus
    template: 
      src: prometheus.yml.j2
      dest: /etc/prometheus/prometheus.yml
    notify: 
      - Restart prometheus service
      - Restart nginx service
    become: yes

  - name: ARGS file
    template:
      src: prometheus
      dest: /etc/default/prometheus
    notify: 
      - Restart prometheus service
      - Restart nginx service
    become: yes