---
  - name: install bind9
    apt:
      name: bind9
      state: latest

  - name: 
    template: 
      src: named.cond.options.j2
      dest: /etc/bind/named.conf.options
    notify: restart bind

  - name:
    template: 
      src: db.gel
      dest: /var/cache/bind/db.spray

  - name: 
    template: 
      src: named.cond.local.j2
      dest: /etc/bind/named.conf.local
    notify: restart bind